AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'Guardfile'
    - 'tmp/**'
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 120

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IndentationConsistency:
  EnforcedStyle: rails

Style/RaiseArgs:
  EnforcedStyle: compact
