# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d46a763e75f6a3c62cae4a86d2eb7e200dbc873559af9fa51669820d928e21cb21ccd846b1b5e5d1c67e4dd52f07514ad2eea0f5f9ec9d25e9a9869534907c8b

test:
  secret_key_base: 838630e2008df62372c123470f618c08a332a916cdc45720077c4c3a4ffa163d489aebc6dfefc2b8e1bb4fce299db3ad009e1663b5dddc6477eba7b8975de7ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
